//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemageDetail
    {
        public int DemageDetailId { get; set; }
        public int DemageMasterId { get; set; }
        public int ProductId { get; set; }
        public int DemageTypeId { get; set; }
        public double DemageQty { get; set; }
        public decimal UnitPrice { get; set; }
        public double TotalPrice { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual DemageMaster DemageMaster { get; set; }
        public virtual Product Product { get; set; }
    }
}
