//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeServicePointMap
    {
        public int EmployeeServicePoinMapId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> ZoneDivisionId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> TerritoryId { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual SubZone SubZone { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ZoneDivision ZoneDivision { get; set; }
        public virtual Area Area { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
