//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSA.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int OID { get; set; }
        public Nullable<int> MemberNo { get; set; }
        public string MemberName { get; set; }
        public string CustomerId { get; set; }
        public string CustomerType { get; set; }
        public string CustomerName { get; set; }
        public string RegistrationNo { get; set; }
        public string NID { get; set; }
        public string BIN { get; set; }
        public string TIN { get; set; }
        public string TradeLicense { get; set; }
        public string Telephone { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string ContactPersonName { get; set; }
        public string ConcatPersonEmail { get; set; }
        public string ContactPersonMobile { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public string Village { get; set; }
        public Nullable<long> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> UpazilaId { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Website { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> OverDueAmount180Days { get; set; }
        public Nullable<decimal> OverDueAmount90Days { get; set; }
        public Nullable<decimal> DuePayment { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public string CustomerStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
