//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSA.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Id { get; set; }
        public string EmployeeId { get; set; }
        public string MemberId { get; set; }
        public string MemberType { get; set; }
        public string MemberName { get; set; }
        public string ContactPersonName { get; set; }
        public string Nationality { get; set; }
        public string ConcatPersonEmail { get; set; }
        public string LogoUrl { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string CorporateOffice { get; set; }
        public string TradeLicense { get; set; }
        public string Website { get; set; }
        public string CompanyChairman { get; set; }
        public string CompanyMD { get; set; }
        public string CompanyName { get; set; }
        public string Telephone { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string OfficeEmail { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string MaritalType { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public string BankBranch { get; set; }
        public string BankAccount { get; set; }
        public string NationalId { get; set; }
        public string Religion { get; set; }
        public string BloodGroup { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
