//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSA.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upazila
    {
        public Nullable<int> DistrictId { get; set; }
        public int UpazilaId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> CarryingRate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual District District { get; set; }
    }
}
