//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsa.lib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BsaAGM
    {
        public int Id { get; set; }
        public Nullable<int> AGMYear { get; set; }
        public string MemberOrDealerId { get; set; }
        public string NameOfDealer { get; set; }
        public string Disrtict { get; set; }
        public string PhoneNo { get; set; }
        public string NameOfRepresentative { get; set; }
        public Nullable<int> NoofPerson { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Email { get; set; }
    }
}
