//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsa.lib.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BSAWebEntities : DbContext
    {
        public BSAWebEntities()
            : base("name=BSAWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BSAEmployee> BSAEmployees { get; set; }
        public virtual DbSet<BSAMember> BSAMembers { get; set; }
        public virtual DbSet<BSAMessage> BSAMessages { get; set; }
        public virtual DbSet<BsaAGM> BsaAGMs { get; set; }
    }
}
